name: themepy-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - attrs=19.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - colorama=0.4.3
  - cryptography=2.5
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - freetype=2.10.2
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - keyring=21.3.0
  - kiwisolver=1.2.0
  - lcms2=2.11
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.1
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - llvm-openmp=10.0.1
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.3
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.0.2u
  - packaging=20.4
  - pandas=1.1.0
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pkginfo=1.5.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.6
  - prompt_toolkit=3.0.6
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.0
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=7.0
  - readme_renderer=24.0
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.28.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - twine=3.2.0
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
prefix: /Users/peter.mckeever/anaconda3/envs/themepy-dev
